<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HAB3M0C" ignored="0" name="Android" tests="3" failures="1" timestamp="2022-08-18T17:56:05 IST" time="30.176" errors="0">
  <testcase name="invalidPassword" time="4.037" classname="com.qa.tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.hkdf]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.hkdf]
at com.qa.tests.LoginTests.invalidPassword(LoginTests.java:97)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- invalidPassword -->
  <testcase name="invalidUsername" time="3.412" classname="com.qa.tests.LoginTests"/>
  <testcase name="successfulLogin" time="4.79" classname="com.qa.tests.LoginTests"/>
</testsuite> <!-- Android -->
